#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#api:
#  # loads routes from the given routing file stored in some bundle
#  resource: 'routes/translations/translations.yaml'
#  prefix: '/api'